sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t courses/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true courses/react-test npm test

after_success:
  - docker build -t courses/multi-client ./client
  - docker build -t courses/multi-nginx ./nginx
  - docker build -t courses/multi-server ./server
  - docker build -t courses/multi-worker ./worker

# log in docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push the images in docker hub
  - docker push courses/multi-client renators/multi-client
  - docker push courses/multi-nginx renators/multi-nginx
  - docker push courses/multi-server renators/multi-server
  - docker push courses/multi-worker renators/multi-worker  